# Generated by Django 5.1.4 on 2025-02-05 16:45

import django.db.models.deletion
import resource.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_uploadedfile_file_size_uploadedfile_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='category',
            field=models.ForeignKey(blank=True, default=resource.models.Category.get_default_category, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.category'),
        ),
    ]
