# Generated by Django 5.1.4 on 2025-02-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_category_uploadedfile_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='category',
        ),
    ]
