# Generated by Django 5.1.4 on 2025-02-08 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0006_folder_uploadedfile_folder'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('name', 'parent')},
        ),
        migrations.AlterUniqueTogether(
            name='uploadedfile',
            unique_together={('name', 'folder')},
        ),
    ]
